# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='owner',
            new_name='admin',
        ),
    ]
