# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20160802_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='friends',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='friend',
            new_name='member',
        ),
    ]
