# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160802_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', through='chat.Membership', to='chat.Friend'),
        ),
    ]
